# Generated by Django 3.1.2 on 2020-12-24 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201224_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpicture',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
