# Generated by Django 3.1.2 on 2020-11-15 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20201115_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpicture',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpicture',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
