# Generated by Django 3.1.2 on 2020-11-15 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201115_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpicture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
