# Generated by Django 3.1.2 on 2020-11-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201115_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpicture',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='userpicture',
            name='user',
        ),
    ]
