# Generated by Django 3.1.2 on 2021-03-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210202_2019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
