# Generated by Django 3.1.2 on 2020-12-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpicture',
            name='picture_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userpicture',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
